### ISSUE TITLE
Fatal error: Parent property of StarterPlayer.StarterCharacterScripts is locked

### ISSUE THREAD

**Issue by EthanMichalicek** [argon-rbx/argon-roblox#1]
A coworker and I have been trying to get Argon 2.0.0-pre2/3 working on our individual machines, but we both have run into this error in the Argon Roblox plugin. Not sure if it matters since this seems to be an internal issue with the plugin interacting with the Roblox engine, but I have been testing on an M1 Macbook and my coworker on a Windows machine.

<img width="877" alt="image" src="https://github.com/argon-rbx/argon-roblox/assets/51338441/e65f4819-e0f7-4789-85c1-67ba03cd00d7">

**Comment by kolson25** [comment]
Also having this issue. I am the coworker :)

**Comment by DervexDev** [comment]
Thanks for the report. Going to fix this in a couple of hours!

**Comment by DervexDev** [comment]
Fixed in d0597b752f225c1b94f3bfa255103eb5072e8f17. Available in `2.0.0-pre3`.
