### ISSUE TITLE
Argon does not sync after closing widget

### ISSUE THREAD

**Issue by SpaceDice9** [argon-rbx/argon-roblox#3]
When closing the plugin's widget, Argon no longer syncs scripts between Roblox Studio and local files. Reopening it does not fix the issue. Occurs on the latest versions of the plugin (v2.0.6) and the VS Code Extension (v2.0.7).

**Comment by DervexDev** [comment]
Fixed in 37a07e8daa73f71c95070ba073c8b493add412da
