### ISSUE TITLE
Argon shows up every single time I launch a place in studio or play a game

### ISSUE THREAD

**Issue by krampuszc** [argon-rbx/argon-roblox#7]
Should be a configuration option or something like that

**Comment by krampuszc** [comment]
I also don't think this is a Roblox issue rather something with plugins themselves like the way they are set etc
![image](https://github.com/user-attachments/assets/185f7942-1f73-45a2-928f-8e5d00144da7)

**Comment by DervexDev** [comment]
Could you dock your window and see if it solves the issue? Also, could you confirm that other plugins e.g. Rojo don't have the same problem? Last time I checked it was a Roblox issue as some of my other plugins did the the same thing.

**Comment by krampuszc** [comment]
> Could you dock your window and see if it solves the issue? Also, could you confirm that other plugins e.g. Rojo don't have the same problem? Last time I checked it was a Roblox issue as some of my other plugins did the the same thing.

Closing it doesn't solve it and it seems to be a plugin issue as some plugins have it and others don't 
rojo only makes a notification if the place previously used rojo
I will try to look into it more

**Comment by DervexDev** [comment]
Could you send a quick recording showcasing this issue? Right now the widget just uses its previous state which I think works correctly:

https://github.com/user-attachments/assets/6512c961-7541-4f67-b221-dc9a6fcb1650

**Comment by krampuszc** [comment]
It always opens up again even if i close it. This is even if i fully close studio
Uploading YAw7CV2rGX.mp4…

**Comment by krampuszc** [comment]
ok i dont know how thats even possible
thanks github

https://github.com/user-attachments/assets/096c84e3-a22c-4135-a49b-793d42d938a6

**Comment by DervexDev** [comment]
It might be a Windows only issue. I don’t think I can do anything to fix this problem at the moment as Argon doesn’t even handle widget position or docking state. Let's leave this issue open for now
